spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/admin
      auto-index-creation: true
  quartz:
    properties:
      org.quartz.jobStore.class: com.novemberain.quartz.mongodb.MongoDBJobStore
      org.quartz.jobStore.mongoUri: mongodb://admin:admin@localhost:27017/admin
      org.quartz.jobStore.dbName: quartz
      org.quartz.jobStore.collectionPrefix: quartz
      org.quartz.threadPool.threadCount: 30
      org.quartz.jobStore.isClustered: true
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.instanceName: zlrx_local_cluster
logging.level.org:
  springframework.scheduling.quartz: DEBUG
  quartz: DEBUG